name: Jet_clean
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas-profiling
  - nb_conda_kernels
  - python=3.8
  - pandas
  - seaborn
  - swifter
  - modin
  - tqdm
  - scikit-optimize
  - scikit-learn=0.22.2.post1
